name: Build and push image

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/calamitouscamel/ti4_map_generator_bot:latest
            ghcr.io/calamitouscamel/ti4_map_generator_bot:${{ github.sha }}
